# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('repository_url', models.URLField()),
                ('last_modified_date', models.DateField()),
                ('report', models.FileField(upload_to='')),
            ],
        ),
    ]
