# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Project'),
        ),
    ]
