# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20170506_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified_date',
            field=models.DateTimeField(),
        ),
    ]
