# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20170507_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='last_modified_date',
            new_name='last_commit_date',
        ),
    ]
