# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20170510_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloned_dir_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
