# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20170515_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='options',
            field=models.TextField(default=''),
        ),
    ]
